### ISSUE TITLE
React 19 support

### ISSUE THREAD

**Issue by Micnubinub** [Mood-al/react-tabs-scrollable#22]
When I updated to react 19 I started getting this error:
`Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')`

**Comment by Genokilller** [comment]
I got it on 18.3, after updating NextJS on the last version (15.x).

**Comment by Mood-al** [comment]
Hey guys, when I have a free time, i will see this issue and try to solve it.

**Comment by DevExplotel** [comment]
Same issue

> Hey guys, when I have a free time, i will see this issue and try to solve it.

**Comment by rioarray** [comment]
I have the same issue in my apps when using version of next and react below
```
"next": "^15.1.4",
"react": "^19.0.0",
"react-dom": "^19.0.0",
```
The error is
```
TypeError: Cannot read properties of undefined (reading 'ReactCurrentDispatcher')
    at eval (react-tabs-scrollable.es.js:253:17)
    at eval (react-tabs-scrollable.es.js:654:6)
    at mr (react-tabs-scrollable.es.js:655:4)
    at eval (react-tabs-scrollable.es.js:657:27)
    at (/en-ae/node_modules/react-tabs-scrollable/dist/react-tabs-scrollable.es.js (https://localhost:3000/_next/static/chunks/_app-pages-browser_components_screens_search-result_widget_index_tsx.js:38:1)
```

**Comment by Mood-al** [comment]
Hey guys, i have added 2.0.8 patch to NPM to fix this issue.
Please install it and tell me if it worked on ur enviroment
run `npm i react-tabs-scrollable@latest` to install it

Thanks!

**Comment by rioarray** [comment]
> Hey guys, i have added 2.0.8 patch to NPM to fix this issue. Please install it and tell me if it worked on ur enviroment run `npm i react-tabs-scrollable@latest` to install it
> 
> Thanks!

Thank you @Mood-al. issue that i found before has gone now 👍 👍
